// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mysql

var TableNames = struct {
	Food string
	Tag  string
	User string
}{
	Food: "Food",
	Tag:  "Tag",
	User: "User",
}
