// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package mysql

var TableNames = struct {
	Food     string
	FoodTags string
	Tag      string
	User     string
}{
	Food:     "Food",
	FoodTags: "FoodTags",
	Tag:      "Tag",
	User:     "User",
}
